#!/bin/bash

BASEDIR="$(dirname $0)/.."
RCFILE="$BASEDIR/share/lxcli.rc"

ISROOT="$(whoami | grep '^root$')"

if [ -n "$ISROOT" ]; then
	screen bash -c "screen -t lxcli 0 bash -i --rcfile $RCFILE"
else
	echo "Root access is required"
fi
