#!/bin/bash

BASEDIR="$(dirname $0)/.."
RCFILE="$BASEDIR/share/lxcli.rc"

ISROOT="$(whoami | grep '^root$')"

if [ -n "$ISROOT" ]; then
	bash -i --rcfile $RCFILE
else
	echo "Root access is required"
fi
